In [1]:
import sys 
import numpy as np
import pandas as pd
print("Python:", sys.version)
print("Numpy:",np.__version__)
print("Pandas:", pd.__version__)

Python: 3.13.1 | packaged by Anaconda, Inc. | (main, Dec 11 2024, 17:02:46) [MSC v.1929 64 bit (AMD64)]
Numpy: 2.5.1
Pandas: 2.3.3

In [2]:
a = 10
b = 3.14
name = "Python"
active = True
print(type(a))
print(type(b))
print(type(name))
print(type(active))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>

In [3]:
numbers = [10, 20, 30]
point = (4, 5)
student = {"name": "An", "score": 8.5}
unique_values = {1, 2, 3, 3}
print(numbers)
print(point)
print(student)
print(unique_values)

[10, 20, 30]
(4, 5)
{'name': 'An', 'score': 8.5}
{1, 2, 3}

In [4]:
x = [10, 20, 30, 40, 50]
print(x[0])
print(x[-1])
print(x[1:4])
print(x[:3])
print(x[::2])

10
50
[20, 30, 40]
[10, 20, 30]
[10, 30, 50]

In [5]:
a = [1, 2, 3]
b = a
b[0] = 100
print(a)
print(b)

[100, 2, 3]
[100, 2, 3]

In [6]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
#attribute
print(arr.shape) 
print(arr.ndim)
print(arr.dtype)
#method
print(arr.sum())
print(arr.mean())

(2, 3)
2
int64
21
3.5

In [7]:
#pd.array?
#pd.read_csv?

In [8]:
%timeit sum(range(1000))
%timeit [x**2 for x in range(1000)]

22.7 μs ± 3 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
101 μs ± 2.41 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [9]:
%pwd
!dir

 Volume in drive C is OS
 Volume Serial Number is 7BFB-2E60

 Directory of C:\Hon\Nam_3_HK1 2026_2027\DataScience\Hoan-Data-Science-Course\notebooks

09/02/2026  03:12 PM    <DIR>          .
08/31/2026  10:24 PM    <DIR>          ..
09/01/2026  09:39 AM    <DIR>          .ipynb_checkpoints
09/02/2026  03:12 PM                34 missing.csv
09/02/2026  03:12 PM            80,877 on_tap_01_python_jupyter.ipynb
09/02/2026  03:07 PM                39 scores_only.csv
09/02/2026  03:00 PM                39 students_output.csv
               4 File(s)         80,989 bytes
               3 Dir(s)  160,290,537,472 bytes free

In [10]:
numbers = [5, 10, 15, 20, 25]
result = [x**2 for x in numbers if x > 10]
print(result)

[225, 400, 625]

In [11]:
import numpy as np
numbers = [5, 10, 15, 20, 25]
arr = np.array(numbers)
print(arr)
print(type(arr))

[ 5 10 15 20 25]
<class 'numpy.ndarray'>

In [12]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

1
(5,)
5
int64

In [13]:
arr = np.array([5, 10, 15, 20, 25])
print(arr[0])
print(arr[2])
print(arr[-1])

5
15
25

In [14]:
arr = np.array([5, 10, 15, 20, 25])
print(arr[:3])
print(arr[1:4])
print(arr[::2])
print(arr[::-1])
#[start : stop : step] stop KHÔNG được lấy

[ 5 10 15]
[10 15 20]
[ 5 15 25]
[25 20 15 10  5]

In [15]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]])
print(matrix[:2, :2])
print(matrix[:, 0]) # : lấy tất cả, -> tất cả hàng cột 0

[[10 20]
 [40 50]]
[10 40 70]

In [16]:
arr = np.array([5, 10, 15, 20, 25])
mask = arr > 10
print(mask)
result = arr**2
print(result[arr>10])
print(result[mask])

[False False  True  True  True]
[225 400 625]
[225 400 625]

In [17]:
arr = np.array([5, 10, 15, 20, 25])
mask = arr > 10
print(mask)

[False False  True  True  True]

In [18]:
arr = np.array([5, 10, 15, 20, 25])
result = arr[arr>10]**2
print(result)

[225 400 625]

In [19]:
arr = np.array([5, 10, 15, 20, 25])
print(arr.sum()) # tong
print(arr.mean()) # trung binh
print(arr.min()) # nho nhat
print(arr.max()) # lon nhat
print(arr.std())

75
15.0
5
25
7.0710678118654755

In [20]:
x = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(x[1, 1:])
print(x[:, 1])
print(x[x > 50])

[50 60]
[20 50 80]
[60 70 80 90]

x[1, 1:]
  ↑  ↑
  │  └─ từ cột 1 trở đi
  └──── hàng 1

x[:, 1]
  ↑  ↑
  │  └─ cột 1
  └──── tất cả hàng

x[x > 50]
   ↑
boolean mask

In [21]:
x = np.array([10, 20, 30, 40, 50])
sub = x[1:4]
print("x =", x)
print("sub =", sub)
sub[0] = 999
print("x =", x)
print("sub =", sub)

x = [10 20 30 40 50]
sub = [20 30 40]
x = [ 10 999  30  40  50]
sub = [999  30  40]

In [22]:
x = np.array([10, 20, 30, 40, 50])
sub = x[1:4].copy()
sub[0] = 999
print('sub =', sub)
print('x =',x)

sub = [999  30  40]
x = [10 20 30 40 50]

In [23]:
x = np.arange(1,13)
print(x)
print(x.shape)
matrix = x.reshape(3,4)
print(matrix)
print(x.reshape(-1,2)) # Cho trước 2 cột, NumPy tự tính ra 6 hàng:
                        # shape: (6, 2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

In [24]:
x = np.arange(12)
a = x.reshape(3,-1)
print(a)
print(a.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)

In [25]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
]) 
print(x.sum())
print(x.sum(axis=0))

21
[5 7 9]

axis=0
→ gộp theo chiều hàng
→ còn lại từng cột

In [26]:
print(x.sum(axis=1))

[ 6 15]

axis=1
→ gộp theo chiều cột
→ còn lại từng hàng

In [27]:
x = np.array([[10, 20, 30],
              [40, 50, 60]])
print(x.mean(axis=0))
print(x.mean(axis=1))

[25. 35. 45.]
[20. 50.]

In [28]:
print(x + 5)
print(x*2)
print(x**2)
print(np.sqrt(x))
print(np.exp(x))
print(np.log(x))

[[15 25 35]
 [45 55 65]]
[[ 20  40  60]
 [ 80 100 120]]
[[ 100  400  900]
 [1600 2500 3600]]
[[3.16227766 4.47213595 5.47722558]
 [6.32455532 7.07106781 7.74596669]]
[[2.20264658e+04 4.85165195e+08 1.06864746e+13]
 [2.35385267e+17 5.18470553e+21 1.14200739e+26]]
[[2.30258509 2.99573227 3.40119738]
 [3.68887945 3.91202301 4.09434456]]

In [29]:
print(x+10)

[[20 30 40]
 [50 60 70]]

In [30]:
x = np.array([[1, 2, 3],
             [4, 5, 6]])
v = np.array([10, 20, 30])
print(x+v)

[[11 22 33]
 [14 25 36]]

In [31]:
x = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(x.sum(axis=0))
print(x.mean(axis=1))
print(x+100)
v = np.array([1, 2, 3])
print(x+v)

[120 150 180]
[20. 50. 80.]
[[110 120 130]
 [140 150 160]
 [170 180 190]]
[[11 22 33]
 [41 52 63]
 [71 82 93]]

In [32]:
x = np.array([5, 10, 15, 20, 25, 30])
print(x>10)
print(x[(x>10) & (x<30)])

[False False  True  True  True  True]
[15 20 25]

In [33]:
print(x[(x < 10) | (x > 25)])

[ 5 30]

In [34]:
print(np.any(x>18))
print(np.all(x>0))
print(np.all(x>10))

True
True
False

any → có ÍT NHẤT một phần tử True?
all → TẤT CẢ có True không?

In [35]:
x = np.array([40, 10, 70, 20, 90])
print(x.max())     # max()     → GIÁ TRỊ lớn nhất -> value
print(x.argmax())  # argmax()  → VỊ TRÍ của giá trị lớn nhất -> index
print(x.min())
print(x.argmin())

90
4
10
1

In [36]:
print(np.sort(x))
print(x)

[10 20 40 70 90]
[40 10 70 20 90]

In [37]:
print(np.argsort(x))
idx = np.argsort(x)
print(x[idx])

[1 3 0 2 4]
[10 20 40 70 90]

In [38]:
print(x[[0,2,4]]) #Fancy Indexing

[40 70 90]

In [39]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate([a, b])
print(c)
a = np.array([[1,2],
              [3,4]])
#2D
b = np.array([
    [5, 6]
])
print(np.vstack([a,b]))

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]

In [40]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [10],
    [20]
])
print(np.hstack([a, b]))

[[ 1  2 10]
 [ 3  4 20]]

In [41]:
x = np.array([45, 80, 67, 92, 38, 75, 88])
print(x[(x>60) & (x<=80)])
print(np.any(x>90))
print(np.max(x))
print(np.argmax(x))
y = np.sort(x)
print(y[-1])
print(y)

[80 67 75]
True
92
3
92
[38 45 67 75 80 88 92]

In [42]:
import pandas as pd
scores = pd.Series([90, 85, 78, 92])

In [43]:
print(scores)
print(type(scores))

0    90
1    85
2    78
3    92
dtype: int64
<class 'pandas.core.series.Series'>

In [44]:
scores = pd.Series(
    [90, 85, 78, 92],
    index=['An', 'Binh', 'Chi', 'Dung'])
print(scores)

An      90
Binh    85
Chi     78
Dung    92
dtype: int64

In [45]:
print(scores.values)
print(scores.index)

[90 85 78 92]
Index(['An', 'Binh', 'Chi', 'Dung'], dtype='object')

In [46]:
print(scores['An'])
print(scores['Chi'])

90
78

In [47]:
print(scores.iloc[0]) #90
print(scores.iloc[2]) # 78
print(scores.iloc[-1]) #92

90
78
92

iloc slicing → stop bị loại
loc slicing  → stop được lấy

In [48]:
print(scores.iloc[0:2])
print(scores.loc['An':'Chi'])

An      90
Binh    85
dtype: int64
An      90
Binh    85
Chi     78
dtype: int64

In [49]:
print(scores>80)
print(scores[scores>80])

An       True
Binh     True
Chi     False
Dung     True
dtype: bool
An      90
Binh    85
Dung    92
dtype: int64

In [50]:
population = {
    'HCM': 9.0,
    'HN': 8.4,
    'DN': 1.2}
s = pd.Series(population)
print(s)

HCM    9.0
HN     8.4
DN     1.2
dtype: float64

In [51]:
scores = pd.Series(
    [7.5, 9.0, 6.5, 8.0, 9.5],
    index=['An', 'Binh', 'Chi', 'Dung', 'Hoa']
)
print(scores['Chi'])
print(scores.iloc[3])
print(scores.loc['Binh':'Dung'])
print(scores[scores>=8])
print(scores.mean())

6.5
8.0
Binh    9.0
Chi     6.5
Dung    8.0
dtype: float64
Binh    9.0
Dung    8.0
Hoa     9.5
dtype: float64
8.1

In [52]:
data = {
    "name": ["An", "Binh", "Chi", "Dung"],
    "age": [20, 21, 19, 22],
    "score": [7.5, 9.0, 6.5, 8.0]
}
df = pd.DataFrame(data)
print(df)

   name  age  score
0    An   20    7.5
1  Binh   21    9.0
2   Chi   19    6.5
3  Dung   22    8.0

In [53]:
print(df.shape) #(4,3)
print(df.columns)
print(df.index) 
print(df.dtypes)

(4, 3)
Index(['name', 'age', 'score'], dtype='object')
RangeIndex(start=0, stop=4, step=1)
name      object
age        int64
score    float64
dtype: object

shape   → số hàng, số cột
columns → tên các cột
index   → nhãn hàng
dtypes  → kiểu dữ liệu từng cột

In [54]:
print(df.head())
print(df.info())
print(df.describe())

   name  age  score
0    An   20    7.5
1  Binh   21    9.0
2   Chi   19    6.5
3  Dung   22    8.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   age     4 non-null      int64
 2   score   4 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 228.0+ bytes
None
             age     score
count   4.000000  4.000000
mean   20.500000  7.750000
std     1.290994  1.040833
min    19.000000  6.500000
25%    19.750000  7.250000
50%    20.500000  7.750000
75%    21.250000  8.250000
max    22.000000  9.000000

head()
→ nhìn dữ liệu

info()
→ cấu trúc, dtype, null

describe()
→ thống kê số

df["score"]
→ Series

df[["score"]]
→ DataFrame

In [55]:
print(df['score'])
print(type(df["score"]))
print(df[["name", "score"]])
print(type(df[["name", "score"]]))

0    7.5
1    9.0
2    6.5
3    8.0
Name: score, dtype: float64
<class 'pandas.core.series.Series'>
   name  score
0    An    7.5
1  Binh    9.0
2   Chi    6.5
3  Dung    8.0
<class 'pandas.core.frame.DataFrame'>

In [56]:
df2 = df.set_index('name')
print(df2)
print(df2.loc["Binh"])

      age  score
name
An     20    7.5
Binh   21    9.0
Chi    19    6.5
Dung   22    8.0
age      21.0
score     9.0
Name: Binh, dtype: float64

In [57]:
print(df2.loc["Binh", "score"]) #df.loc[row, column]
print(df2.loc["An":"Binh"])
print(df2.loc["An":"Binh", ["age","score"]])

9.0
      age  score
name
An     20    7.5
Binh   21    9.0
      age  score
name
An     20    7.5
Binh   21    9.0

In [58]:
print(df.iloc[0])
print(type(df.iloc[0]))
print(df.iloc[0,2])
print(df)
print(df.iloc[0:2, 0:2])

name      An
age       20
score    7.5
Name: 0, dtype: object
<class 'pandas.core.series.Series'>
7.5
   name  age  score
0    An   20    7.5
1  Binh   21    9.0
2   Chi   19    6.5
3  Dung   22    8.0
   name  age
0    An   20
1  Binh   21

In [59]:
print(df[(df["score"]>=8) & (df["age"]>21)])

   name  age  score
3  Dung   22    8.0

In [60]:
df["passsed"] = df["score"]>=5
df["score_plus_1"] = df["score"]+1
print(df)

   name  age  score  passsed  score_plus_1
0    An   20    7.5     True           8.5
1  Binh   21    9.0     True          10.0
2   Chi   19    6.5     True           7.5
3  Dung   22    8.0     True           9.0

In [61]:
df = df.drop(columns=["score_plus_1"])
print(df)

   name  age  score  passsed
0    An   20    7.5     True
1  Binh   21    9.0     True
2   Chi   19    6.5     True
3  Dung   22    8.0     True

In [62]:
print(df.sort_values("score"))
print(df.sort_values("score", ascending=False))

   name  age  score  passsed
2   Chi   19    6.5     True
0    An   20    7.5     True
3  Dung   22    8.0     True
1  Binh   21    9.0     True
   name  age  score  passsed
1  Binh   21    9.0     True
3  Dung   22    8.0     True
0    An   20    7.5     True
2   Chi   19    6.5     True

In [63]:
students = pd.DataFrame({
    "name": ["An", "Binh", "Chi", "Dung", "Hoa"],
    "age": [20, 22, 19, 21, 23],
    "score": [7.0, 9.0, 6.5, 8.5, 9.5]
})
print(students)
print(students.shape)
print(students["score"])
print(students.iloc[2])
print(students[students["score"] >= 8])
print(students[(students["score"] >= 8) & (students["age"]>=21)])
students['passed'] = students['score']>=5
print(students)
print(students.sort_values("score", ascending=False))
print(students.sort_values("score", ascending=False).head(2))

   name  age  score
0    An   20    7.0
1  Binh   22    9.0
2   Chi   19    6.5
3  Dung   21    8.5
4   Hoa   23    9.5
(5, 3)
0    7.0
1    9.0
2    6.5
3    8.5
4    9.5
Name: score, dtype: float64
name     Chi
age       19
score    6.5
Name: 2, dtype: object
   name  age  score
1  Binh   22    9.0
3  Dung   21    8.5
4   Hoa   23    9.5
   name  age  score
1  Binh   22    9.0
3  Dung   21    8.5
4   Hoa   23    9.5
   name  age  score  passed
0    An   20    7.0    True
1  Binh   22    9.0    True
2   Chi   19    6.5    True
3  Dung   21    8.5    True
4   Hoa   23    9.5    True
   name  age  score  passed
4   Hoa   23    9.5    True
1  Binh   22    9.0    True
3  Dung   21    8.5    True
0    An   20    7.0    True
2   Chi   19    6.5    True
   name  age  score  passed
4   Hoa   23    9.5    True
1  Binh   22    9.0    True

In [64]:
%pwd
!dir

 Volume in drive C is OS
 Volume Serial Number is 7BFB-2E60

 Directory of C:\Hon\Nam_3_HK1 2026_2027\DataScience\Hoan-Data-Science-Course\notebooks

09/02/2026  03:12 PM    <DIR>          .
08/31/2026  10:24 PM    <DIR>          ..
09/01/2026  09:39 AM    <DIR>          .ipynb_checkpoints
09/02/2026  03:12 PM                34 missing.csv
09/02/2026  03:12 PM            80,877 on_tap_01_python_jupyter.ipynb
09/02/2026  03:07 PM                39 scores_only.csv
09/02/2026  03:00 PM                39 students_output.csv
               4 File(s)         80,989 bytes
               3 Dir(s)  160,290,529,280 bytes free

In [65]:
from pathlib import Path

PYDATA = Path(
    "../../TaiLieuGoc/pydata-book-3rd-edition"
)

df = pd.read_csv(PYDATA / "examples" / "ex1.csv")
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [66]:
path = PYDATA/"examples"/"ex2.csv"
print(path.read_text())
df = pd.read_csv(path, header=None)
df

1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

header=None

→ Pandas không coi dòng đầu là tên cột

→ tự đặt cột 0, 1, 2, 3, 4

In [67]:
names = ['a', 'b', 'c', 'd', 'message']
df = pd.read_csv(PYDATA/'examples'/'ex2.csv', names=names)
print(df.columns)
df

Index(['a', 'b', 'c', 'd', 'message'], dtype='object')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [68]:
df = pd.read_csv(PYDATA/'examples'/'ex2.csv', 
                 names = names, 
                 index_col = 'message')
print(df.index)
print(df.columns)
df

Index(['hello', 'world', 'foo'], dtype='object', name='message')
Index(['a', 'b', 'c', 'd'], dtype='object')

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [69]:
path = PYDATA/'examples'/'ex3.txt'
print(path.read_text())
result = pd.read_csv(path, sep=r'\s+')
result

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [70]:
path = PYDATA/'examples'/'ex4.csv'
print(path.read_text())

# hey!
a,b,c,d,message
# just wanted to make things more difficult for you
# who reads CSV files with computers, anyway?
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [71]:
df = pd.read_csv(path, skiprows=[0, 2, 3])
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [72]:
path = PYDATA/'examples'/'ex5.csv'
print(path.read_text())
result = pd.read_csv(path)
result
pd.isna(result)
pd.isna(result).sum()

something,a,b,c,d,message
one,1,2,3,4,NA
two,5,6,,8,world
three,9,10,11,12,foo

something    0
a            0
b            0
c            1
d            0
message      1
dtype: int64

In [73]:
result = pd.read_csv(PYDATA/'examples'/'ex5.csv', na_values=['NULL'])
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [74]:
result = pd.read_csv(PYDATA/'examples'/'ex5.csv', keep_default_na = False)
print(result)
print(result.isna())
result2 = pd.read_csv(PYDATA/'examples'/'ex5.csv', 
                     keep_default_na = False,
                     na_values=['NA'])
print(result2)
print(result2.isna())

  something  a   b   c   d message
0       one  1   2   3   4      NA
1       two  5   6       8   world
2     three  9  10  11  12     foo
   something      a      b      c      d  message
0      False  False  False  False  False    False
1      False  False  False  False  False    False
2      False  False  False  False  False    False
  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       two  5   6       8   world
2     three  9  10  11  12     foo
   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False  False  False    False
2      False  False  False  False  False    False

In [75]:
sentinels = {
    'message': ['foo', 'NA'],
    'something': ['two']}
result = pd.read_csv(PYDATA/'examples'/'ex5.csv',
                     na_values=sentinels,
                     keep_default_na=False)
print(result)

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       NaN  5   6       8   world
2     three  9  10  11  12     NaN

Cơ chế hoạt động:

Tại cột message: Các ô có giá trị là "foo" hoặc "NA" sẽ bị biến thành NaN.

Tại cột something: Chỉ ô có giá trị "two" bị biến thành NaN.

Các cột còn lại (như a, b, c, d): 
Giữ nguyên giá trị gốc vì không nằm trong từ điển và đã đặt keep_default_na=False.

Điểm cần nhớ của Cells 67–75 chỉ là:

header=None          → file không có header

names=               → tự đặt tên cột

index_col=           → chọn cột làm index

sep=                 → ký tự phân cách

skiprows=            → bỏ dòng

isna()               → kiểm tra missing

na_values=           → quy định giá trị nào là missing

keep_default_na=     → bật/tắt quy tắc NA mặc định

In [76]:
import numpy as np

x = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(x.shape)
print(x.ndim)
print(x.size)
print(x.dtype)
print(x[1,1])
print(x[:, 1])
print(x[1:, :2])
print(x[(x>=40) & (x<80)])
print(x.sum(axis=0))
print(x.mean(axis=1))
v = np.array([1, 2, 3])
print(x+v)
a = np.array([10, 20, 30, 40])
b = a[1:3]
#view
b[0] = 999
print(a) # [10, 999, 30, 40]
print(b) # [999, 30]
a = np.array([10, 20, 30, 40])
b = a[1:3]
#copy
b = a[1:3].copy()
b[0] = 999
print(a)  # [10, 20, 30, 40]
print(b)  # [999, 30]

(3, 3)
2
9
int64
50
[20 50 80]
[[40 50]
 [70 80]]
[40 50 60 70]
[120 150 180]
[20. 50. 80.]
[[11 22 33]
 [41 52 63]
 [71 82 93]]
[ 10 999  30  40]
[999  30]
[10 20 30 40]
[999  30]

In [77]:
import pandas as pd

df = pd.DataFrame({
    "name": ["An", "Binh", "Chi", "Dung", "Hoa"],
    "age": [20, 22, 19, 21, 23],
    "score": [7.5, 9.0, 6.5, 8.5, 9.5]
})
#In shape, columns, dtypes.
print(df.shape)
print(df.columns)
print(df.dtypes)
#Lấy riêng cột score. Sau đó cho biết kết quả là Series hay DataFrame.
print(df['score'])
print(type(df['score']))
#Dùng .iloc lấy hàng của Chi.
print(df.iloc[2])

#Đặt name làm index vào một DataFrame mới tên df2, 
#rồi dùng .loc lấy score của "Dung".
df2 = df.set_index('name')
print(df2.loc['Dung', 'score'])
print(df[(df['age']>=21)&(df['score']>=8)])
df['passed']=df['score']>=8
top2 = df.sort_values('score', ascending=False).head(2)
print(top2)
df

(5, 3)
Index(['name', 'age', 'score'], dtype='object')
name      object
age        int64
score    float64
dtype: object
0    7.5
1    9.0
2    6.5
3    8.5
4    9.5
Name: score, dtype: float64
<class 'pandas.core.series.Series'>
name     Chi
age       19
score    6.5
Name: 2, dtype: object
8.5
   name  age  score
1  Binh   22    9.0
3  Dung   21    8.5
4   Hoa   23    9.5
   name  age  score  passed
4   Hoa   23    9.5    True
1  Binh   22    9.0    True

   name  age  score  passed
0    An   20    7.5   False
1  Binh   22    9.0    True
2   Chi   19    6.5   False
3  Dung   21    8.5    True
4   Hoa   23    9.5    True

In [78]:
from pathlib import Path
import pandas as pd
PYDATA = Path(
    '../../TaiLieuGoc/pydata-book-3rd-edition'
)
df1 = pd.read_csv(PYDATA/'examples'/'ex1.csv')
print(df1)
print(df1.shape)
names = ['a', 'b', 'c', 'd', 'message']
df2 = pd.read_csv(PYDATA/'examples'/'ex2.csv', names = names)
print(df2)
df3 = pd.read_csv(PYDATA/'examples'/'ex2.csv',
                  names = names,
                  index_col = ['message'])
print(df3)
df4 = pd.read_csv(PYDATA/'examples'/'ex4.csv', skiprows = [0, 2, 3])
print(df4)
df5 = pd.read_csv(PYDATA/'examples'/'ex5.csv')
print(df5.isna().sum())

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo
(3, 5)
   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo
         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12
   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo
something    0
a            0
b            0
c            1
d            0
message      1
dtype: int64

Câu 6: Giải thích sự khác nhau giữa keep_default_na=True và keep_default_na=False

keep_default_na=True
→ sử dụng danh sách giá trị NA mặc định của Pandas.
→ nếu có thêm na_values, các giá trị đó được bổ sung.

keep_default_na=False
→ không sử dụng danh sách NA mặc định.
→ nếu có na_values, chỉ những giá trị mình chỉ định
  mới được coi là missing.

In [79]:
path = PYDATA/'examples'/'ex6.csv'
df = pd.read_csv(path, nrows=5)
print(df)
print(df.shape)

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q
(5, 5)

In [80]:
df = pd.read_csv(path)
print(df.shape)
df.head()

(10000, 5)

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [81]:
chunker = pd.read_csv(path, chunksize=1000)
print(type(chunker))

<class 'pandas.io.parsers.readers.TextFileReader'>

In [82]:
chunker = pd.read_csv(path, chunksize=1000)
#for piece in chunker:
#    print(piece.shape)
for piece in chunker:
    print(type(piece))
    print(piece.head())
    break

<class 'pandas.core.frame.DataFrame'>
        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [83]:
chunker = pd.read_csv(
    path,
    chunksize=1000
)

tot = pd.Series([], dtype="int64")

for piece in chunker:
    counts = piece["key"].value_counts()

    tot = tot.add(
        counts,
        fill_value=0
    )

tot = tot.sort_values(
    ascending=False
)

tot

key
E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
M    338.0
J    337.0
F    335.0
K    334.0
H    330.0
V    328.0
I    327.0
U    326.0
P    324.0
D    320.0
A    320.0
R    318.0
Y    314.0
G    308.0
S    308.0
N    306.0
W    305.0
T    304.0
B    302.0
Z    288.0
C    286.0
4    171.0
6    166.0
7    164.0
8    162.0
3    162.0
5    157.0
2    152.0
0    151.0
9    150.0
1    146.0
dtype: float64

In [84]:
chunker = pd.read_csv(path, chunksize=1000)
total_rows = 0
for piece in chunker:
    total_rows += len(piece)
print(total_rows)
print(pd.read_csv(path).shape[0])

10000
10000

In [85]:
data = pd.DataFrame({
    'name': ['An', 'Binh', 'Chi'],
    'score': [7.5, 9.0, 6.5]})
output_path = 'students_output.csv'
print(data)
data.to_csv(output_path)
!dir

   name  score
0    An    7.5
1  Binh    9.0
2   Chi    6.5
 Volume in drive C is OS
 Volume Serial Number is 7BFB-2E60

 Directory of C:\Hon\Nam_3_HK1 2026_2027\DataScience\Hoan-Data-Science-Course\notebooks

09/02/2026  03:12 PM    <DIR>          .
08/31/2026  10:24 PM    <DIR>          ..
09/01/2026  09:39 AM    <DIR>          .ipynb_checkpoints
09/02/2026  03:12 PM                34 missing.csv
09/02/2026  03:12 PM            80,877 on_tap_01_python_jupyter.ipynb
09/02/2026  03:07 PM                39 scores_only.csv
09/02/2026  03:13 PM                46 students_output.csv
               4 File(s)         80,996 bytes
               3 Dir(s)  160,289,087,488 bytes free

In [86]:
data.to_csv('students_output.csv', index=False)
pd.read_csv('students_output.csv')

   name  score
0    An    7.5
1  Binh    9.0
2   Chi    6.5

In [87]:
data2 = pd.DataFrame({
    "name": ["An", "Binh", "Chi"],
    "age": [20, 22, 19],
    "score": [7.5, 9.0, 6.5]
})
data2.to_csv('scores_only.csv', index=False, columns=['name', 'score'])
pd.read_csv('scores_only.csv')

   name  score
0    An    7.5
1  Binh    9.0
2   Chi    6.5

In [88]:
import numpy as np

data3 = pd.DataFrame({
    "a": [1, 2, np.nan],
    "b": [4, np.nan, 6]
})
print(data3)
data3.to_csv('missing.csv', index=False, na_rep='NULL')
data.to_csv(sys.stdout, na_rep='NULL')

     a    b
0  1.0  4.0
1  2.0  NaN
2  NaN  6.0
,name,score
0,An,7.5
1,Binh,9.0
2,Chi,6.5